owner: aeqe
repo: upptime

sites:
  - name: git
    url: $ENDPOINT_GIT
  - name: r6
    url: https://r6.patriick.dev

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - zImPatrick
